spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: 'jdbc:h2:mem:db'
    username: ecom
    password: 123
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true

  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

stripe:
  secret:
        key: ${STRIPE_SECRET_KEY}
  webhook:
        secret: ${WEBHOOK_SECRET_KEY}
server:
  port: 8080
