spring:
  profiles:
    active: dev

  application:
    name: E-com application (Amazon marketplace)

  # JPA - sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


# swagger - documentation

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: "/v3/api-docs"
  show-actuator: true

# stripe - payment

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${WEBHOOK_SECRET_KEY}

# JWT - token

jwt:
  secret: ${JWT_SECRET}
  #  secret: 4a7b9c2d8e3f1a6b5c0d9e4f7a2b8c3d6e1f4a7b9c2d8e3f1a6b5c0d9e4f7a2b
  expiration: 900000

# version

server:
  servlet:
    context-path: "/api/v1"