spring:
  application:
    name: product-service
  profiles:
    active: dev

  #RabbitMQ

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

jwt:
  internalSecretKey: ${JWT_INTERNAL_SECRET_KEY}